apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-proxy-nginx-config
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            server_name _;

            location / {
                auth_basic "Authentication Required";
                auth_basic_user_file /etc/nginx/htpasswd-secret/htpasswd;

                proxy_pass http://phpmyadmin-service:80;
            }
        }
    }