apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-proxy-nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location / {
            auth_basic "Authentication Required";
            auth_basic_user_file /etc/nginx/conf.d/htpasswd;

            proxy_pass http://phpmyadmin-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }