apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- ../../base/phpmyadmin/phpmyadmin-deployment.yaml
- ../../base/phpmyadmin/phpmyadmin-service.yaml
- ../../base/phpmyadmin/phpmyadmin-ingress.yaml