apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - mysql-configmap.yaml
  - mysql-statefulset.yaml
  - migration-job.yaml
