apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization #comment
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - mysql/mysql-configmap.yaml
  - mysql/mysql-pv-claim.yaml
  - mysql/mysql-statefulset.yaml
  - mysql/mysql-secret.yaml
