apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: ghcr.io/Suprath/docker-demo:latest # This will be replaced by CI/CD
        command: ["php", "artisan", "migrate", "--force"]
        env:
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: "mysql-primary"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "laravel"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
      restartPolicy: Never
  backoffLimit: 4